Repository kubernetes-csi/csi-proxy, pull requests merged in 2020-09, with the labels that each got.

#65 Implementing volume v1beta1 api including VolumeStats api
  Makefile
  client/api/disk/v1alpha1/api.proto
  client/api/disk/v1beta1/api.pb.go
  client/api/disk/v1beta1/api.proto
  client/api/volume/v1beta1/api.pb.go
  client/api/volume/v1beta1/api.proto
  client/groups/disk/v1beta1/client_generated.go
  client/groups/volume/v1beta1/client_generated.go
  integrationtests/volume_test.go
  internal/os/disk/api.go
  internal/os/volume/api.go
  internal/server/disk/internal/types.go
  internal/server/disk/internal/types_generated.go
  internal/server/disk/internal/v1beta1/conversion.go
  internal/server/disk/internal/v1beta1/conversion_generated.go
  internal/server/disk/internal/v1beta1/server_generated.go
  internal/server/disk/server.go
  internal/server/volume/api_group_generated.go
  internal/server/volume/internal/types.go
  internal/server/volume/internal/types_generated.go
  internal/server/volume/internal/v1beta1/conversion.go
  internal/server/volume/internal/v1beta1/conversion_generated.go
  internal/server/volume/internal/v1beta1/server_generated.go
  internal/server/volume/server.go
  internal/server/volume/server_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/XXL

#70 Add Beta changelog
  CHANGELOG/CHANGELOG-0.2.0.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#72 add andyzhangx as approver
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#74 fix: failing unit tests in `./internal/...`
  internal/server/volume/server_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, ok-to-test, release-note-none, size/S

#50 fix typos
  internal/os/disk/api.go
  internal/os/smb/api.go
  internal/os/volume/api.go
  internal/server/disk/server.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, ok-to-test, release-note-none, size/S

#73 doc: add issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/support.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#75 fix: smb valid path error
  internal/server/smb/server.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#76 Beta APIs for FileSystem and SMB APIGroups
  client/api/filesystem/v1beta1/api.pb.go
  client/api/filesystem/v1beta1/api.proto
  client/api/smb/v1beta1/api.pb.go
  client/api/smb/v1beta1/api.proto
  client/groups/filesystem/v1beta1/client_generated.go
  client/groups/smb/v1beta1/client_generated.go
  integrationtests/filesystem_test.go
  integrationtests/smb_test.go
  internal/server/filesystem/api_group_generated.go
  internal/server/filesystem/internal/v1beta1/conversion.go
  internal/server/filesystem/internal/v1beta1/conversion_generated.go
  internal/server/filesystem/internal/v1beta1/server_generated.go
  internal/server/smb/api_group_generated.go
  internal/server/smb/internal/v1beta1/conversion.go
  internal/server/smb/internal/v1beta1/conversion_generated.go
  internal/server/smb/internal/v1beta1/server_generated.go
Labels: approved, cncf-cla: yes, kind/api-change, lgtm, release-note, size/XXL

#77 Add Beta.1 Changelog
  CHANGELOG/CHANGELOG-0.2.1.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S
