Repository kubernetes-csi/csi-proxy, pull requests merged in 2020-08, with the labels that each got.

#61 ListDiskIDs API
  .gitignore
  client/api/disk/v1beta1/api.pb.go
  client/api/disk/v1beta1/api.proto
  client/go.mod
  client/go.sum
  client/groups/disk/v1beta1/client_generated.go
  go.mod
  go.sum
  integrationtests/disk_test.go
  integrationtests/smb_test.go
  integrationtests/volume_test.go
  internal/os/disk/api.go
  internal/server/disk/api_group_generated.go
  internal/server/disk/internal/types.go
  internal/server/disk/internal/types_generated.go
  internal/server/disk/internal/v1beta1/conversion.go
  internal/server/disk/internal/v1beta1/conversion_generated.go
  internal/server/disk/internal/v1beta1/server_generated.go
  internal/server/disk/server.go
  internal/shared/disk/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XXL

#66 fix: SMB remount issue
  internal/os/filesystem/api.go
  internal/os/filesystem/api_test.go
  internal/server/filesystem/server.go
  internal/server/filesystem/server_test.go
  internal/server/smb/server.go
  internal/server/smb/server_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M

#68 add smb csi driver link
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#67 test: add windows unit test pipeline
  .github/workflows/windows.yml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S
