Repository kubernetes-csi/csi-proxy, pull requests merged in 2020-10, with the labels that each got.

#86 Update README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#89 Bump go version to 1.13 in go.mod
  go.mod
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#84 Add WriteVolumeCache API
  client/api/volume/v1beta2/api.pb.go
  client/api/volume/v1beta2/api.proto
  client/groups/volume/v1beta2/client_generated.go
  integrationtests/volume_test.go
  internal/os/volume/api.go
  internal/server/volume/api_group_generated.go
  internal/server/volume/internal/types.go
  internal/server/volume/internal/types_generated.go
  internal/server/volume/internal/v1beta2/conversion.go
  internal/server/volume/internal/v1beta2/conversion_generated.go
  internal/server/volume/internal/v1beta2/server_generated.go
  internal/server/volume/server.go
  internal/server/volume/server_test.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/volume/v1beta2/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/volume/v1beta2/api.proto
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XXL

#92 Add writevolumecache into Dismount API
  internal/os/volume/api.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#81 Add v1alpha1 system API
  client/api/system/v1alpha1/api.pb.go
  client/api/system/v1alpha1/api.proto
  client/groups/system/v1alpha1/client_generated.go
  cmd/csi-proxy/main.go
  integrationtests/system_test.go
  internal/os/system/api.go
  internal/server/system/api_group_generated.go
  internal/server/system/internal/types.go
  internal/server/system/internal/types_generated.go
  internal/server/system/internal/v1alpha1/conversion.go
  internal/server/system/internal/v1alpha1/conversion_generated.go
  internal/server/system/internal/v1alpha1/server_generated.go
  internal/server/system/server.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/system/v1alpha1/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/system/v1alpha1/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/system/v1alpha1/client_generated.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XL

#94 Fix error string to not be VM specific
  internal/os/system/api.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#90 CI: Enable integration tests on Windows
  .github/workflows/windows.yml
  integrationtests/api_groups_test.go
  integrationtests/csi_api_gen_test.go
  integrationtests/disk_test.go
  integrationtests/filesystem_test.go
  integrationtests/utils.go
  integrationtests/volume_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#95 Adding GetAttachState and SetAttachState to disk api group
  client/api/disk/v1beta2/api.pb.go
  client/api/disk/v1beta2/api.proto
  client/groups/disk/v1beta2/client_generated.go
  integrationtests/disk_test.go
  internal/os/disk/api.go
  internal/server/disk/api_group_generated.go
  internal/server/disk/internal/types.go
  internal/server/disk/internal/types_generated.go
  internal/server/disk/internal/v1beta2/conversion.go
  internal/server/disk/internal/v1beta2/conversion_generated.go
  internal/server/disk/internal/v1beta2/server_generated.go
  internal/server/disk/server.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/disk/v1beta2/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/disk/v1beta2/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/disk/v1beta2/client_generated.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/XXL

#96 Update Dismount function
  internal/os/volume/api.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#88 master: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/build.make
  release-tools/cloudbuild.sh
  release-tools/cloudbuild.yaml
  release-tools/filter-junit.go
  release-tools/prow.sh
  release-tools/travis.yml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#97 Add service commands to system api group
  client/api/system/v1alpha1/api.pb.go
  client/api/system/v1alpha1/api.proto
  client/groups/system/v1alpha1/client_generated.go
  integrationtests/system_test.go
  internal/os/system/api.go
  internal/server/system/internal/types.go
  internal/server/system/internal/types_generated.go
  internal/server/system/internal/v1alpha1/conversion_generated.go
  internal/server/system/internal/v1alpha1/server_generated.go
  internal/server/system/server.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/system/v1alpha1/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/system/v1alpha1/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/system/v1alpha1/client_generated.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/XXL

#91 noop when resize is called and size of partition is >= requested size
  internal/os/volume/api.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/M

#98 fix: add trailing backslash to remote path when linking to SMB shares
  internal/os/smb/api.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/XS

#100 Improvements to the System API group
  client/api/system/v1alpha1/api.pb.go
  client/api/system/v1alpha1/api.proto
  integrationtests/system_test.go
  internal/server/system/internal/types.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/system/v1alpha1/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/system/v1alpha1/api.proto
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XL

#101 Changelog for Beta.2 release
  CHANGELOG/CHANGELOG-0.2.2.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S
