Repository kubernetes-csi/csi-proxy, pull requests merged in 2020-03, with the labels that each got.

#29 Request to add KK to approver list
  OWNERS
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#23 SMB APIs
  client/api/smb/v1alpha1/api.pb.go
  client/api/smb/v1alpha1/api.proto
  client/groups/smb/v1alpha1/client_generated.go
  cmd/server/main.go
  go.mod
  go.sum
  integrationtests/smb_test.go
  internal/os/smb/api.go
  internal/server/smb/api_group_generated.go
  internal/server/smb/internal/types.go
  internal/server/smb/internal/types_generated.go
  internal/server/smb/internal/v1alpha1/conversion.go
  internal/server/smb/internal/v1alpha1/conversion_generated.go
  internal/server/smb/internal/v1alpha1/server_generated.go
  internal/server/smb/server.go
  internal/server/smb/server_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XXL

#30 Fix smb test
  integrationtests/smb_test.go
  internal/server/smb/server_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#22 Enable unit test
  .prow.sh
  Makefile
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#32 Update README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#31 Add getDiskNumberbyDiskName into disk API
  client/api/disk/v1alpha1/api.pb.go
  client/api/disk/v1alpha1/api.proto
  client/groups/disk/v1alpha1/client_generated.go
  internal/os/disk/api.go
  internal/server/disk/internal/types.go
  internal/server/disk/internal/types_generated.go
  internal/server/disk/internal/v1alpha1/conversion_generated.go
  internal/server/disk/internal/v1alpha1/server_generated.go
  internal/server/disk/server.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#16 Expand README
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#35 Smb changes to add linking to local path and Stat fix
  client/api/disk/v1alpha1/api.pb.go
  client/api/smb/v1alpha1/api.pb.go
  client/api/smb/v1alpha1/api.proto
  cmd/server/main.go
  internal/os/filesystem/api.go
  internal/os/smb/api.go
  internal/server/filesystem/server.go
  internal/server/smb/internal/types.go
  internal/server/smb/internal/v1alpha1/conversion_generated.go
  internal/server/smb/server.go
  internal/server/smb/server_test.go
Labels: approved, cncf-cla: yes, kind/api-change, kind/bug, lgtm, release-note-none, size/L

#38 update release tool
  .prow.sh
  Makefile
  go.mod
  go.sum
  integrationtests/smb_test.go
  internal/os/disk/api.go
  internal/server/disk/internal/types.go
  internal/server/disk/server.go
  release-tools/README.md
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/build.make
  release-tools/go-get-kubernetes.sh
  release-tools/prow.sh
  release-tools/travis.yml
  release-tools/update-vendor.sh
  release-tools/verify-go-version.sh
  release-tools/verify-vendor.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XL

#40 Update README
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/XS

#42 Update Makefile to specify build platform
  Makefile
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#43 Change name to csi-proxy
  Makefile
  cmd/csi-proxy/main.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#39 Update readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#41 Add logs
  cmd/csi-proxy/main.go
  cmd/csi-proxy/version.go
  internal/os/disk/api.go
  internal/os/smb/api.go
  internal/os/volume/api.go
  internal/server/disk/server.go
  internal/server/filesystem/server.go
  internal/server/server.go
  internal/server/smb/server.go
  internal/server/volume/server.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#45 doc: add azurefile-csi-driver in Supported CSI Drivers
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/XS

#44 Git ignore bin directory
  .gitignore
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#47 Update Readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S
