Repository kubernetes-csi/csi-proxy, pull requests merged in 2021-06, with the labels that each got.

#141 master: update release-tools + OWNERS
  OWNERS
  OWNERS_ALIASES
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/OWNERS
  release-tools/OWNERS_ALIASES
  release-tools/build.make
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
  release-tools/verify-shellcheck.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#145 Don't count reserved partitions (gpt) when checking if any exist
  internal/os/disk/api.go
  internal/server/disk/server.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/S

#147 Close Open disk file handles
  internal/os/disk/api.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/M

#146 Changes in the SMB v1beta2 API
  client/api/smb/v1beta2/api.pb.go
  client/api/smb/v1beta2/api.proto
  integrationtests/smb_test.go
  integrationtests/smb_v1alpha1_test.go
  integrationtests/smb_v1beta1_test.go
  integrationtests/smb_v1beta2_test.go
  internal/os/smb/api.go
  internal/server/smb/internal/types.go
  internal/server/smb/internal/v1alpha1/conversion_generated.go
  internal/server/smb/internal/v1beta1/conversion_generated.go
  internal/server/smb/internal/v1beta2/conversion_generated.go
  internal/server/smb/server.go
  internal/server/smb/server_test.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/smb/v1beta2/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/smb/v1beta2/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/smb/v1alpha1/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/smb/v1beta1/client_generated.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, release-note, size/XL

#150 Combine plugin and pod paths into one KubeletPath
  .github/workflows/windows.yml
  client/api/filesystem/v1beta2/api.pb.go
  client/api/filesystem/v1beta2/api.proto
  cmd/csi-proxy/main.go
  integrationtests/filesystem_v1alpha1_test.go
  integrationtests/filesystem_v1beta1_test.go
  integrationtests/filesystem_v1beta2_test.go
  integrationtests/utils.go
  internal/server/filesystem/internal/types.go
  internal/server/filesystem/internal/v1alpha1/conversion_generated.go
  internal/server/filesystem/internal/v1beta1/conversion_generated.go
  internal/server/filesystem/internal/v1beta2/conversion_generated.go
  internal/server/filesystem/server.go
  internal/server/filesystem/server_test.go
  internal/server/smb/server_test.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v1beta2/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v1beta2/api.proto
Labels: approved, cncf-cla: yes, kind/api-change, lgtm, release-note, size/XL

#151 Update references to old cli args in the docs
  README.md
  docs/DEVELOPMENT.md
  scripts/e2e-runner.ps1
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#154 Send arrays to ConvertTo-Json in the internal disk implementation
  pkg/os/disk/api.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/S

#156 cloud build: create work directory
  .cloudbuild.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#157 Changelog for 1.0 RC1 release
  CHANGELOG/CHANGELOG-1.0.0-rc1.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#148 upload csiproxy binary to gcs with version information
  .cloudbuild.sh
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
