Repository kubernetes-csi/csi-proxy, pull requests merged in 2021-05, with the labels that each got.

#127 Fix IsVolumeFormatted issue on checking volume type "Unknown"
  internal/os/volume/api.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#135 master: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/go-get-kubernetes.sh
  release-tools/prow.sh
  release-tools/pull-test.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#136 Replace and correct imports in integration tests
  .cloudbuild.sh
  cmd/csi-proxy/version.go
  integrationtests/apigroups/server/dummy/server.go
  integrationtests/iscsi_test.go
  integrationtests/smb_test.go
  internal/server/server.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#137 Remove redundant alias import and replace few function names in ISCSI server
  integrationtests/apigroups/server/dummy/internal/v1alpha1/conversion.go
  integrationtests/disk_test.go
  integrationtests/filesystem_test.go
  integrationtests/iscsi_test.go
  internal/server/disk/internal/v1alpha1/conversion.go
  internal/server/disk/internal/v1beta1/conversion.go
  internal/server/disk/internal/v1beta2/conversion.go
  internal/server/disk/internal/v1beta3/conversion.go
  internal/server/volume/internal/v1beta1/conversion.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#138 Update Volume API
  client/api/volume/v1beta3/api.pb.go
  client/api/volume/v1beta3/api.proto
  client/groups/volume/v1beta3/client_generated.go
  integrationtests/csi_api_gen_test.go
  integrationtests/disk_test.go
  integrationtests/system_test.go
  integrationtests/utils.go
  integrationtests/volume_test.go
  integrationtests/volume_v1alpha1_test.go
  integrationtests/volume_v1beta1_test.go
  integrationtests/volume_v1beta2_test.go
  integrationtests/volume_v1beta3_test.go
  internal/os/volume/api.go
  internal/server/volume/internal/types.go
  internal/server/volume/internal/types_generated.go
  internal/server/volume/internal/v1alpha1/conversion.go
  internal/server/volume/internal/v1alpha1/conversion_generated.go
  internal/server/volume/internal/v1beta1/conversion.go
  internal/server/volume/internal/v1beta1/conversion_generated.go
  internal/server/volume/internal/v1beta2/conversion.go
  internal/server/volume/internal/v1beta2/conversion_generated.go
  internal/server/volume/internal/v1beta3/conversion_generated.go
  internal/server/volume/internal/v1beta3/server_generated.go
  internal/server/volume/server.go
  internal/server/volume/server_test.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/volume/v1beta3/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/volume/v1beta3/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/volume/v1alpha1/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/volume/v1beta1/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/volume/v1beta2/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/volume/v1beta3/client_generated.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XXL
