Repository kubernetes-csi/csi-proxy, pull requests merged in 2021-04, with the labels that each got.

#125 update readme for beta
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#123 Fix issue in isVolumeFormatted function
  internal/os/volume/api.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#124 Add another client per API that can communicate with a custom named pipe
  client/go.mod
  client/go.sum
  client/groups/disk/v1/client_generated.go
  client/groups/disk/v1alpha1/client_generated.go
  client/groups/disk/v1beta1/client_generated.go
  client/groups/disk/v1beta2/client_generated.go
  client/groups/filesystem/v1/client_generated.go
  client/groups/filesystem/v1alpha1/client_generated.go
  client/groups/filesystem/v1beta1/client_generated.go
  client/groups/iscsi/v1alpha1/client_generated.go
  client/groups/iscsi/v1alpha2/client_generated.go
  client/groups/smb/v1/client_generated.go
  client/groups/smb/v1alpha1/client_generated.go
  client/groups/smb/v1beta1/client_generated.go
  client/groups/system/v1alpha1/client_generated.go
  client/groups/volume/v1/client_generated.go
  client/groups/volume/v1alpha1/client_generated.go
  client/groups/volume/v1beta1/client_generated.go
  client/groups/volume/v1beta2/client_generated.go
  cmd/csi-proxy-api-gen/generators/client_generated_gen.go
  go.mod
  go.sum
  integrationtests/apigroups/client/dummy/v1/client_generated.go
  integrationtests/apigroups/client/dummy/v1alpha1/client_generated.go
  integrationtests/apigroups/client/dummy/v1alpha2/client_generated.go
  integrationtests/apigroups/server/dummy/api_group_generated.go
  integrationtests/apigroups/server/dummy/internal/v1/server_generated.go
  internal/server/disk/api_group_generated.go
  internal/server/disk/internal/v1/server_generated.go
  internal/server/filesystem/api_group_generated.go
  internal/server/filesystem/internal/v1/server_generated.go
  internal/server/smb/api_group_generated.go
  internal/server/smb/internal/v1/server_generated.go
  internal/server/volume/api_group_generated.go
  internal/server/volume/internal/v1/server_generated.go
  vendor/github.com/Microsoft/go-winio/go.mod
  vendor/github.com/Microsoft/go-winio/go.sum
  vendor/github.com/Microsoft/go-winio/pipe.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/go.mod
  vendor/github.com/kubernetes-csi/csi-proxy/client/go.sum
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/disk/v1/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/filesystem/v1/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/iscsi/v1alpha2/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/smb/v1/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/system/v1alpha1/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/volume/v1/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/volume/v1alpha1/client_generated.go
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/Makefile
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/go113.go
  vendor/github.com/pkg/errors/stack.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XL

#129 Update build instructions in the readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#128 Make GPT the new partition style for volumes. Normalize windows paths in SMB apis to support linux style paths in source.
  integrationtests/volume_test.go
  internal/os/disk/api.go
  internal/server/smb/server.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/S
