Repository kubernetes-csi/csi-proxy, pull requests merged in 2021-01, with the labels that each got.

#109 Update gs bucket
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#108 Fix Typo
  README.md
Labels: approved, cncf-cla: yes, do-not-merge/release-note-label-needed, lgtm, ok-to-test, size/XS

#110 Support binary Disk IDs
  internal/os/disk/api.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/S

#106 Add asciiflow diagram to the csi-proxy
  README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, release-note-none, size/M
