Repository kubernetes-csi/csi-proxy, pull requests merged in 2021-07, with the labels that each got.

#160 master: update release-tools
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#162 Updates node-driver-registrar image tag in README.md
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#164 Changelog for v1 release
  CHANGELOG/CHANGELOG-1.0.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#166 Add Apache 2.0 license to the client module
  client/LICENSE
  client/apiversion/version.go
  client/utils.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#167 Automated cherry pick of #166: Add Apache 2.0 license to the client module
  client/LICENSE
  client/apiversion/version.go
  client/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#168 Sync client module to the vendor directory
  vendor/github.com/kubernetes-csi/csi-proxy/client/LICENSE
  vendor/github.com/kubernetes-csi/csi-proxy/client/apiversion/version.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/utils.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/L
