Repository kubernetes-csi/csi-proxy, pull requests merged in 2022-10, with the labels that each got.

#220 release-tools are updated.
  release-tools/prow.sh
Labels: cncf-cla: yes, release-note-none, lgtm, size/S, approved

#229 Add mauriciopoppe to owners
  OWNERS
Labels: cncf-cla: yes, release-note-none, lgtm, kind/cleanup, size/XS, approved

#228 Update GitHub action to be branch agnostic
  .github/workflows/windows.yml
Labels: cncf-cla: yes, release-note-none, lgtm, kind/cleanup, size/XS, ok-to-test, approved

#230 Sync v1 to master in preparation for moving master to v2
  .github/workflows/windows.yml
  OWNERS
  release-tools/prow.sh
Labels: cncf-cla: yes, release-note-none, lgtm, kind/cleanup, size/M, ok-to-test, approved

#231 Migrate filesystem API Group to library model
  integrationtests/filesystem_test.go
  integrationtests/utils.go
  pkg/filesystem/api/api.go
  pkg/filesystem/api/api_test.go
  pkg/filesystem/filesystem.go
  pkg/filesystem/filesystem_test.go
  pkg/filesystem/types.go
  pkg/filesystem/utils.go
  pkg/utils/utils.go
  scripts/utils.sh
Labels: size/XXL, cncf-cla: yes, release-note-none, lgtm, ok-to-test, kind/api-change, approved

#233 Migrate disk API group to library model
  integrationtests/disk_test.go
  pkg/disk/api/api.go
  pkg/disk/api/types.go
  pkg/disk/disk.go
  pkg/disk/types.go
Labels: size/XXL, cncf-cla: yes, release-note-none, lgtm, ok-to-test, kind/api-change, approved

#240 Migrate volume API group to library model
  integrationtests/utils.go
  integrationtests/volume_test.go
  integrationtests/volume_v2alpha1_test.go
  pkg/volume/api/api.go
  pkg/volume/types.go
  pkg/volume/volume.go
  pkg/volume/volume_test.go
Labels: size/XXL, cncf-cla: yes, release-note-none, lgtm, ok-to-test, kind/api-change, approved

#244 Migrate system API group to library model
  integrationtests/system_test.go
  pkg/system/api/api.go
  pkg/system/api/types.go
  pkg/system/system.go
  pkg/system/types.go
Labels: cncf-cla: yes, release-note-none, lgtm, size/L, ok-to-test, kind/api-change, approved

#245 feat: migrate smb API group to library model
  integrationtests/smb_test.go
  pkg/smb/api/api.go
  pkg/smb/smb.go
  pkg/smb/smb_test.go
  pkg/smb/types.go
Labels: cncf-cla: yes, release-note-none, lgtm, size/XL, kind/api-change, approved

#247 Migrate iscsi API group to library model
  integrationtests/iscsi_test.go
  pkg/iscsi/api/api.go
  pkg/iscsi/api/types.go
  pkg/iscsi/iscsi.go
  pkg/iscsi/types.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/iscsi/v1alpha2/client_generated.go
  vendor/modules.txt
Labels: cncf-cla: yes, release-note-none, lgtm, size/XL, kind/api-change, approved

#254 Document API group interface methods
  pkg/disk/disk.go
  pkg/filesystem/filesystem.go
  pkg/iscsi/iscsi.go
  pkg/smb/smb.go
  pkg/system/system.go
  pkg/volume/volume.go
Labels: cncf-cla: yes, kind/documentation, release-note-none, lgtm, size/M, approved

#258 Rename Smb to SMB
  integrationtests/smb_test.go
  pkg/smb/api/api.go
  pkg/smb/smb.go
  pkg/smb/smb_test.go
  pkg/smb/types.go
Labels: cncf-cla: yes, release-note-none, lgtm, size/L, kind/api-change, approved

#257 Remove compatibility methods for old API versions
  pkg/disk/api/api.go
  pkg/disk/disk.go
  pkg/disk/types.go
  pkg/filesystem/filesystem.go
  pkg/filesystem/types.go
  pkg/volume/types.go
  pkg/volume/volume.go
Labels: cncf-cla: yes, release-note-none, lgtm, kind/cleanup, size/L, approved

#266 Document structs used in API group interfaces
  pkg/disk/types.go
  pkg/filesystem/types.go
  pkg/iscsi/types.go
  pkg/smb/types.go
  pkg/system/types.go
  pkg/volume/types.go
Labels: cncf-cla: yes, kind/documentation, release-note-none, lgtm, size/L, approved

#269 Rename iqn to IQN
  integrationtests/iscsi_ps_scripts.go
  integrationtests/iscsi_test.go
  pkg/iscsi/api/api.go
  pkg/iscsi/iscsi.go
  pkg/iscsi/types.go
Labels: cncf-cla: yes, release-note-none, lgtm, kind/cleanup, size/M, approved

#270 Rename Id to ID
  integrationtests/utils.go
  integrationtests/volume_test.go
  pkg/volume/types.go
  pkg/volume/volume.go
  pkg/volume/volume_test.go
Labels: cncf-cla: yes, release-note-none, lgtm, size/L, kind/api-change, approved

#262 Delete Makefile checks from GitHub actions
  .github/workflows/windows.yml
Labels: kind/failing-test, cncf-cla: yes, release-note-none, lgtm, size/XS, approved

#273 Rename typo in file name
  pkg/filesystem/hostapi/hostapi.go
Labels: cncf-cla: yes, release-note-none, lgtm, kind/cleanup, size/XS, approved

#274 test: migrate tests to HostProcess pods
  scripts/integration-test.yaml
  scripts/utils.sh
Labels: kind/feature, cncf-cla: yes, release-note-none, lgtm, size/M, approved

#277 Add pointer in README to v2 branch
  README.md
Labels: cncf-cla: yes, kind/documentation, release-note-none, lgtm, size/XS, approved

#276 Update documentation for v2 release
  README.md
  docs/API.md
  docs/CSI-Proxy.png
  docs/DEVELOPMENT.md
  docs/USAGE.md
  docs/apis/disk_v1.md
  docs/apis/filesystem_v1.md
  docs/apis/smb_v1.md
  docs/apis/volume_v1.md
  docs/csi-proxy-high-level-arch.png
Labels: size/XXL, cncf-cla: yes, kind/documentation, release-note-none, lgtm, approved

#279 Modify Makefile to compile integration test
  Makefile
Labels: cncf-cla: yes, release-note-none, lgtm, kind/cleanup, size/XS, approved

#280 doc: add top level comment for GitHub action
  .github/workflows/windows.yml
Labels: cncf-cla: yes, kind/documentation, release-note-none, lgtm, size/XS, approved

#281 Remove indentation on commands in README
  README.md
Labels: cncf-cla: yes, kind/documentation, release-note-none, lgtm, size/S, approved

#282 chore: remove artifacts from cloudbuild
  cloudbuild.yaml
Labels: cncf-cla: yes, release-note-none, lgtm, kind/cleanup, size/XS, approved
