Repository kubernetes-csi/csi-proxy, pull requests merged in 2022-01, with the labels that each got.

#182 Update CSI Proxy dev scripts
  docs/DEVELOPMENT.md
  scripts/e2e-runner.ps1
  scripts/e2e-tests.sh
  scripts/sync-csi-proxy.ps1
  scripts/sync-csi-proxy.sh
Labels: cncf-cla: yes, kind/documentation, release-note-none, lgtm, size/L, approved

#188 Bump volume api from v1 to v2alpha1
  client/api/volume/v2alpha1/api.pb.go
  client/api/volume/v2alpha1/api.proto
  client/groups/volume/v2alpha1/client_generated.go
  integrationtests/volume_test.go
  integrationtests/volume_v2alpha1_test.go
  pkg/server/volume/api_group_generated.go
  pkg/server/volume/impl/v2alpha1/conversion.go
  pkg/server/volume/impl/v2alpha1/conversion_generated.go
  pkg/server/volume/impl/v2alpha1/server_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/volume/v2alpha1/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/volume/v2alpha1/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/volume/v2alpha1/client_generated.go
  vendor/modules.txt
Labels: kind/feature, size/XXL, cncf-cla: yes, release-note, lgtm, approved

#187 Bump Filesystem API from v1 to v2alpha1
  client/api/filesystem/v2alpha1/api.pb.go
  client/api/filesystem/v2alpha1/api.proto
  client/groups/filesystem/v2alpha1/client_generated.go
  integrationtests/filesystem_test.go
  integrationtests/filesystem_v2alpha1_test.go
  pkg/server/filesystem/api_group_generated.go
  pkg/server/filesystem/impl/v2alpha1/conversion.go
  pkg/server/filesystem/impl/v2alpha1/conversion_generated.go
  pkg/server/filesystem/impl/v2alpha1/server_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v2alpha1/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v2alpha1/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/filesystem/v2alpha1/client_generated.go
  vendor/modules.txt
Labels: kind/feature, size/XXL, cncf-cla: yes, release-note, lgtm, approved

#184 Add the --working-dir repeated flag
  README.md
  cmd/csi-proxy/main.go
  pkg/server/filesystem/server.go
  pkg/server/filesystem/server_test.go
  pkg/server/smb/server_test.go
Labels: kind/feature, cncf-cla: yes, release-note, lgtm, size/M, approved

#191 Filesystem server accepts an array of working dirs only, log on startup
  cmd/csi-proxy/main.go
  pkg/server/filesystem/server.go
  pkg/server/filesystem/server_test.go
  pkg/server/smb/server_test.go
Labels: cncf-cla: yes, release-note-none, lgtm, kind/cleanup, size/S, approved

#194 Autostart CSI proxy on boot
  README.md
  scripts/sync-csi-proxy.ps1
Labels: cncf-cla: yes, release-note, kind/documentation, lgtm, size/XS, ok-to-test, approved

#192 master: update release-tools
  release-tools/build.make
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
Labels: cncf-cla: yes, release-note-none, lgtm, size/M, approved

#186 Add RmdirContents API in the Fileystem v2alpha1 API Group
  Makefile
  client/api/filesystem/v2alpha1/api.pb.go
  client/api/filesystem/v2alpha1/api.proto
  client/groups/filesystem/v2alpha1/client_generated.go
  integrationtests/filesystem_v2alpha1_test.go
  pkg/os/filesystem/api.go
  pkg/server/filesystem/impl/types.go
  pkg/server/filesystem/impl/types_generated.go
  pkg/server/filesystem/impl/v2alpha1/conversion_generated.go
  pkg/server/filesystem/impl/v2alpha1/server_generated.go
  pkg/server/filesystem/server.go
  pkg/server/filesystem/server_test.go
  pkg/server/smb/server_test.go
  scripts/bump-version.sh
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v2alpha1/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v2alpha1/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/filesystem/v2alpha1/client_generated.go
Labels: kind/feature, cncf-cla: yes, release-note, lgtm, size/XL, kind/api-change, approved
