Repository kubernetes-csi/csi-proxy, pull requests merged in 2024-12, with the labels that each got.

#362 Prow update master
  release-tools/build.make
  release-tools/prow.sh
  release-tools/pull-test.sh
Labels: cncf-cla: yes, release-note-none, lgtm, kind/cleanup, size/M, ok-to-test, approved

#363 Add min go runtime to be 1.23 and add godebug winsymlink=0
  .github/workflows/windows.yml
  go.mod
  go.sum
Labels: kind/feature, cncf-cla: yes, release-note, lgtm, size/S, approved

#364 fix: unnecessary resize volume error
  pkg/os/volume/api.go
Labels: kind/bug, cncf-cla: yes, release-note, lgtm, size/XS, approved
